language: node_js
node_js:
  "8"
before_script:
  - npm install
script:
  - ./node_modules/.bin/gulp test
# branches:
#   only:
#     - master
# notifications:
#   email:
#     - sjcarbon@lbl.gov
#     - cjmungall@lbl.gov
